var express = require('express');
var router = express.Router();

var authController = require('./../controllers/authController');

/* USER SCHEMA */
/**
* @swagger 
* components:
*   schemas:
*       User:
*           type: object
*           required: 
*               - userId          
*               - name          
*               - surname          
*               - email          
*               - password          
*           properties: 
*               userId:           
*                   type: integer           
*                   description: Primary Key. Autogenerated Id          
*               name:           
*                   type: string                   
*               surname:           
*                   type: string                   
*               email:           
*                   type: string                   
*               password:           
*                   type: string                   
*               role:           
*                   type: string           
*                   description: Enum ['admin', 'user'], user by default           
*/


/* SIGN UP API */
/**
* @swagger 
* /api/auth/signup:
*   post:
*       summary: Create a new User
*       tags: [Auth]
*       requestBody:
*           required: true
*           content:
*               application/json:    
*                   schema:    
*                       type: object    
*                       required: 
*                           - name          
*                           - surname          
*                           - email          
*                           - password          
*                       properties:        
*                           name:           
*                               type: string                   
*                           surname:           
*                               type: string                   
*                           email:           
*                               type: string                   
*                           password:           
*                               type: string  
* 
*       responses:
*           201:
*               description: Signed up!
*           401:
*               description: User already registered
*           500:
*               description: Internal Error
*/
router.post('/signup', authController.signUp);

/* SIGN IN API */
/**
* @swagger 
* /api/auth/signin:
*   post:
*       summary: Sign in a user
*       tags: [Auth]
*       requestBody:
*           required: true
*           content:
*               application/json:    
*                   schema:    
*                       type: object    
*                       required:          
*                           - email          
*                           - password          
*                       properties:                         
*                           email:           
*                               type: string                   
*                           password:           
*                               type: string  
* 
*       responses:
*           200:
*               description: Signed in!
*           401:
*               description: Wrong user or password
*           500:
*               description: Internal Error
*/
router.post('/signin', authController.signIn);

module.exports = router